name: cloud-agent
description: Cloud-based AI agent for Agenda Aqui project
version: 1.0.0

# Agent configuration
agent:
  type: cloud
  model: gpt-4
  capabilities:
    - code-review
    - code-generation
    - testing
    - documentation
    - refactoring

# Instructions and context
instructions: |
  You are a specialized cloud agent for the Agenda Aqui project, a multi-tenant 
  scheduling SaaS for beauty professionals.
  
  ## Your Responsibilities:
  
  1. **Code Review**: Review code changes following clean architecture principles
  2. **Code Generation**: Generate code following the project's conventions
  3. **Testing**: Create and maintain tests for use cases
  4. **Documentation**: Update and maintain technical documentation
  5. **Refactoring**: Improve code quality while maintaining functionality
  
  ## Project Context:
  
  - Stack: Next.js 14+, TypeScript, Supabase, Tailwind CSS
  - Architecture: Clean Architecture (use cases, ports, adapters)
  - Conventions: Always use centavos for money, UTC for dates in backend
  - Dates: ALWAYS consult docs/DATE-HANDLING-GUIDE.md before manipulating dates
  - Style: Tailwind CSS only, no custom CSS files, light mode PRIORITÁRIO
  
  ## Key Rules:
  
  - Follow the conventions in `.github/copilot-instructions.md`
  - Use cases must be pure and testable
  - Routes should be thin controllers
  - Always create tests for new use cases
  - Money values in centavos, dates in UTC (backend)
  - Use Tailwind CSS classes only (no custom CSS)
  
  ## Code Quality Standards:
  
  - TypeScript strict mode
  - No single-letter variables
  - Named types/interfaces for DTOs
  - Small, focused functions
  - Early returns for error cases
  - Composition over inheritance

# Scopes where this agent can be invoked
scopes:
  - code-review
  - implementation
  - testing
  - documentation
  - refactoring
  - architecture

# File patterns this agent should focus on
file_patterns:
  - "src/**/*.ts"
  - "src/**/*.tsx"
  - "src/domain/use-cases/**/*"
  - "src/infra/adapters/**/*"
  - "src/app/**/*"
  - "*.test.ts"
  - "*.spec.ts"
  - "docs/**/*.md"

# Tools and integrations
tools:
  - name: typescript
    enabled: true
  - name: jest
    enabled: true
  - name: eslint
    enabled: true
  - name: supabase-cli
    enabled: true

# Quality gates
quality_gates:
  - build: required
  - lint: required
  - type-check: required
  - tests: required

# Delegation rules
delegation:
  enabled: true
  auto_delegate:
    - pattern: "src/domain/use-cases/**"
      reason: "Complex business logic requiring specialized review"
    - pattern: "supabase/migrations/**"
      reason: "Database changes requiring careful review"
    - pattern: "**/*.test.ts"
      reason: "Test coverage and quality assurance"
