name: agenda-aqui-workspace
description: Workspace configuration for Agenda Aqui GitHub Copilot agents

# Workspace-level settings
workspace:
  name: agenda-aqui
  type: saas-multi-tenant
  domain: scheduling-beauty-professionals
  
# Available agents in this workspace
agents:
  - name: cloud-agent
    file: cloud-agent.yml
    primary: true
    
# Global agent settings
settings:
  # Default agent to use when not specified
  default_agent: cloud-agent
  
  # Enable automatic agent delegation
  auto_delegation:
    enabled: true
    
  # Agent selection rules (example syntax - adjust based on GitHub Copilot's actual routing API)
  routing:
    # Use cloud agent for complex tasks
    - condition: "complexity > medium"
      agent: cloud-agent
      
    # Use cloud agent for use cases
    - condition: "path.startsWith('src/domain/use-cases')"
      agent: cloud-agent
      
    # Use cloud agent for database migrations
    - condition: "path.startsWith('supabase/migrations')"
      agent: cloud-agent
      
    # Use cloud agent for architecture changes
    - condition: "scope == 'architecture'"
      agent: cloud-agent

# Shared context for all agents
shared_context:
  # Project conventions
  conventions:
    money: "Always use centavos (number) in domain, formatPrice() in UI"
    dates: "UTC in backend, local timezone in UI - ALWAYS consult docs/DATE-HANDLING-GUIDE.md before manipulating dates"
    phone: "Always format with mask (XX) XXXXX-XXXX"
    css: "Tailwind CSS only, no custom CSS files"
    theme: "Light mode PRIORITÁRIO - NEVER use dark: as default, only as optional fallback"
    
  # Architecture layers
  architecture:
    routes: "Thin controllers - validation + use case call"
    use_cases: "Pure business logic, testable"
    services: "SSR/BFF composition with React cache"
    adapters: "Implement ports, no business logic"
    shared: "DTOs, validators, utilities"
    
  # Quality standards
  quality:
    typescript: strict
    testing: "Always create tests for use cases"
    naming: "Descriptive names, no single letters"
    functions: "Small, focused, clear parameters"
    imports: "Organized, no lint warnings"
    
  # Code patterns
  patterns:
    composition_over_inheritance: true
    early_returns: true
    named_types: true
    extract_complexity: true

# Integration settings
integrations:
  github:
    auto_review: true
    review_on_pr: true
    
  supabase:
    cli_command: "npx supabase"
    
  build:
    command: "npm run build"
    
  test:
    command: "npm run test"
    
  lint:
    command: "npm run lint"
    
  type_check:
    command: "npm run type-check"

# Monitoring and metrics
monitoring:
  track_delegations: true
  track_response_time: true
  track_quality_metrics: true
